#3 agents - monitor - 1 signal
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-3agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 500 --total-runs 500 --reset-no-better 10 --max-reset-learning 3 >> result3-monitors
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-3agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 800 --total-runs 800 --reset-no-better 10 --max-reset-learning 3 >> result3-monitors
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-3agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 1000 --total-runs 1000 --reset-no-better 10 --max-reset-learning 3 >> result3-monitors
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-3agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 1500 --total-runs 1500 --reset-no-better 10 --max-reset-learning 3 >> result3-monitors
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-3agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 2000 --total-runs 2000 --reset-no-better 10 --max-reset-learning 3 >> result3-monitors
#4 agents - monitor - 1 signal
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-4agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 500 --total-runs 500 --reset-no-better 10 --max-reset-learning 3 >> result4-monitors
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-4agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 1000 --total-runs 1000 --reset-no-better 10 --max-reset-learning 3 >> result4-monitors
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-4agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 1500 --total-runs 1500 --reset-no-better 10 --max-reset-learning 3 >> result4-monitors
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-4agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 2000 --total-runs 2000 --reset-no-better 10 --max-reset-learning 3 >> result4-monitors
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-4agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 3000 --total-runs 3000 --reset-no-better 10 --max-reset-learning 3 >> result4-monitors
#5 agents - monitor - 1 signal
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-5agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 1000 --total-runs 1000 --reset-no-better 10 --max-reset-learning 3 >> result5-monitors
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-5agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 2000 --total-runs 2000 --reset-no-better 10 --max-reset-learning 3 >> result5-monitors
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-5agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 3000 --total-runs 3000 --reset-no-better 10 --max-reset-learning 3 >> result5-monitors
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-5agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 5000 --total-runs 5000 --reset-no-better 10 --max-reset-learning 3 >> result5-monitors
#6 agents - monitor - 1 signal
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-6agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 2000 --total-runs 2000 --reset-no-better 10 --max-reset-learning 3 >> result6-monitors
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-6agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 5000 --total-runs 5000 --reset-no-better 10 --max-reset-learning 3 >> result6-monitors
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-6agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 8000 --total-runs 8000 --reset-no-better 10 --max-reset-learning 3 >> result6-monitors
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-6agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 15000 --total-runs 15000 --reset-no-better 10 --max-reset-learning 3 >> result6-monitors
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-6agents-monitors.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 20000 --total-runs 20000 --reset-no-better 10 --max-reset-learning 3 >> result6-monitors
