#5 agents
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-5agents.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 10000 --total-runs 10000 --reset-no-better 10 --max-reset-learning 3 >> result5
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-5agents.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 20000 --total-runs 20000 --reset-no-better 10 --max-reset-learning 3 >> result5
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-5agents.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 30000 --total-runs 30000 --reset-no-better 10 --max-reset-learning 3 >> result5
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-5agents.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 40000 --total-runs 40000 --reset-no-better 10 --max-reset-learning 3 >> result5
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-5agents.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 50000 --total-runs 50000 --reset-no-better 10 --max-reset-learning 3 >> result5
#6 agents
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-6agents.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 20000 --total-runs 20000 --reset-no-better 10 --max-reset-learning 3 >> result6
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-6agents.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 40000 --total-runs 40000 --reset-no-better 10 --max-reset-learning 3 >> result6
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-6agents.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 60000 --total-runs 60000 --reset-no-better 10 --max-reset-learning 3 >> result6
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-6agents.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 80000 --total-runs 80000 --reset-no-better 10 --max-reset-learning 3 >> result6
UPPAAL_EXTERNAL_LEARNER_LIBRARY=~/Rong/mcrl_models/libexternal_learning.so ../stratego/verifyta -u ~/Rong/mcrl_models/learning-6agents.xml -D 0.01 --learning-method -1 -s --max-iterations 30 --eval-runs 100 --good-runs 100000 --total-runs 100000 --reset-no-better 10 --max-reset-learning 3 >> result6
